sudo: required
services: 
  - docker

before_install: 
  - docker build -t amashr/amashr-frontend-app -f Dockerfile.dev .

language: generic
deploy: 
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "amashr-frontend"
  env: "AmashrFrontend-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-018302955701"
  bucket_path: "amashr-frontend"
  on: 
    branch: release
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY