version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev .
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules
      - .:/app
    command: ["yarn", "start"]